name: Epochalypse

on:
  schedule:
    - cron: "14 0 * * *"
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Send message
        run: bun run src/index.ts
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
